name: usach-monitor
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - requests>=2.31.0
  - pandas>=2.0.0
  - plotly>=5.15.0
  - dash>=2.14.0
  - flask>=2.3.0
  - matplotlib>=3.7.0
  - python-dateutil>=2.8.1
  - pathlib2>=2.3.0
  - urllib3>=1.26.0
  - certifi>=2020.12.5
  - chardet>=4.0.0
  - idna>=2.10
  - pip
  - pip:
    - dash-bootstrap-components>=1.4.0 